name = "Baumkuchen"
uuid = "e1e568c4-3a56-40a4-95fa-9b9c6c16fccb"
authors = ["Nikolas Siccha <nikolassiccha@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[weakdeps]
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"

[extensions]
TermExt = "Term"
